### ISSUE TITLE
Separating declarations and selectors on new lines

### ISSUE THREAD

**Issue by zannain** [Crilan/prj-rev-bwfs-dasmoto#4]
When multiple selectors are going to receive a common style, per the [Google HTML/CSS style guide](https://google.github.io/styleguide/htmlcssguide.html#Selector_and_Declaration_Separation) it is considered best practice to separate the selectors and declarations with a new line

_Before_
```css
h1, h2, h3, p, span{
  font-family: Helvetica;
}
```

_After_
```css
h1, 
h2, 
h3, 
p, 
span {
  font-family: Helvetica;
}
```

Styles guides are excellent resources to refer to ensure you are following best practices and also staying current with changes in the languages.
